baseurl = "https://echinoid.jp"
languageCode = "ja"
DefaultContentLanguage = "ja"
title = "Hayate TANAKA"
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"

# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
  description = "棘皮動物ウニ綱の分類学を研究する田中颯の個人サイトです。論文・学会発表・著書などの業績情報を掲載しています。"
  mainSections = ["post", "posts"]
  logo        = "img/avatar-icon.png"
  favicon     = "img/favicon.ico"
  dateFormat  = "January 2, 2006"
  commit      = false
  rss         = true
  comments    = false
  readingTime = false
  wordCount   = false
  useHLJS     = true
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false

[[Params.bigimg]]
  src  = "images/header.png"
  desc = "Sea Urchins"

[Params.author]
  name    = "田中颯 (Hayate Tanaka)"
  website = "hayate-tanaka.github.io"
  facebook = "tanaka.hayate"
  github   = "hayate-tanaka"
  twitter  = "HTanattyo"

[[menu.main]]
  name   = "About"
  url    = "page/about/"
  weight = 1

[[menu.main]]
  name   = "CV"
  url    = "page/outputs/"
  weight = 2
